name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.USERNAME_SECRET }}/lab05
        if: ${{ success() }}

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.USERNAME_SECRET }}
          password: ${{ secrets.PASSWORD_SECRET }}

      - name: Push Docker Image
        run: docker push ${{ secrets.USERNAME_SECRET }}/lab05
        if: success() 